### PR TITLE
Update profile.py

### PR DESCRIPTION
**Pull request by BobinMathew**

### CODE REVIEW

**Comment by cafca** [comment]
Welcome @BobinMathew, thank you for your pull request, it is much appreciated. You may have noticed that the tests are failing but that has nothing to do with your pull request, it is a [different issue](#511).

Please fill out our pull request template (find a copy below) in the description of your pull request. In particular I would like to know how you tested this change. Can you point to documentation that confirms that changing the field from NullBoolean to Boolean introduces no side effects? 

Thank you!

**Please copy to your description and fill out:**

```
Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List updates to dependencies that are
required for this change.

Closes # (issue)

## How Has This Been Tested?

Our testing suite runs automatically on this pull request. For many reasons it
can be helpful to perform additional, manual tests in order to make sure that
results are as expected. If you did so, please list theses additional checks
here so we can try and reproduce them or eventually add them to our testing
environment.

- Test A
- Test B

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
```

**Comment by cafca** [comment]
I have fixed some issues that prevented checks to run successfully on this pull request on the upstream master branch. Could you merge from upstream master into your branch to see if the checks succeed now? Please just say a word if you require any assistance.

**Comment by BobinMathew** [comment]
Hi @cafca sorry for the late reply, I not that familiar with docker, so I am still learning that part...
 
> Please fill out our pull request template (find a copy below) in the description of your pull request. In particular I would like to know how you tested this change. Can you point to documentation that confirms that changing the field from NullBoolean to Boolean introduces no side effects?

I haven't completely checked it. But from this [link](https://django.readthedocs.io/en/stable/ref/checks.html) ' I think' their wont be any side effects because they are encouraging the developers to move to the new keyword.
osp_pic1

**Comment by cafca** [comment]
Alright, I can see that you looked up the error code. And actually I can't find any further documentation on this change. 

Another thing that is important here is to add a migration. When you change a Django model, but you are working with existing data in a database that still uses the old model, you have to create a script to migrate the database to the new model version that you created. Django can create such a script automatically. You can read up on Django migrations [here](https://docs.djangoproject.com/en/3.1/topics/migrations/). Especially the introduction and the sections "The commands" and "Adding migrations to apps". 

However, you will need to get Docker running in order to do this. Please tell me if you have any specific issues with that. I am glad to help.

**Comment by cafca** [comment]
Hey @BobinMathew, unfortunately I had to go ahead and solve this issue on my own as the migrations were still missing in this pull request. I hope I have not discouraged you from learning Django. Please know that your contributions to this project are still very welcome. Let me know if I can help you find good issues to help out with and learn some Django at the same time.

**Comment by cafca** [comment]
Superseded by https://github.com/FixMyBerlin/fixmy.platform/pull/556

**Pull request closed without merging**
